"""avatar_hash

Revision ID: 4d2bf53232e3
Revises: 023cd25942d4
Create Date: 2023-03-29 16:58:02.400304

"""

# revision identifiers, used by Alembic.
revision = '4d2bf53232e3'
down_revision = '023cd25942d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
