"""user_token_conf

Revision ID: a9785dde81b2
Revises: 4bf2aa191a20
Create Date: 2023-03-17 15:09:16.688522

"""

# revision identifiers, used by Alembic.
revision = 'a9785dde81b2'
down_revision = '4bf2aa191a20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
