"""post html body

Revision ID: d7d32c60837f
Revises: 00e8414fa6e0
Create Date: 2023-04-04 21:34:09.246329

"""

# revision identifiers, used by Alembic.
revision = 'd7d32c60837f'
down_revision = '00e8414fa6e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
